In [1]:
import datasets
from lets_plot import *
import pandas as pd
import duckdb
LetsPlot.setup_html()

In [61]:
import glob

files = sorted(glob.glob("./mixed_*.jsonl"))

df = pd.concat(
    [pd.read_json(file, lines=True) for file in files],
    ignore_index=True,
).reset_index().rename(columns={"index": "sample_id"})

In [62]:
df

,sample_id,query,positive,negative_1,negative_2,negative_3,negative_4,domain
0,0,Nepal ma first time citizenship certificate ap...,नेपालको स्थानीय प्रशासनमा नागरिकले पहिलो पटक न...,नेपालको स्थानीय प्रशासनमा नागरिकता प्रमाणपत्रक...,नेपालमा विदेशमा बस्ने नागरिकले आफ्नो नागरिकता ...,नेपालको गाउँपालिकामा नागरिकता प्रमाणपत्र बनाउँ...,नेपालको कानून अनुसार नागरिकता प्रमाणपत्र हराएम...,Nepal civic services
1,1,सामान्य वयस्कलाई constipation रोक्न daily fibe...,कब्जियत रोक्न खानामार्फत फाइबर र पानीको भूमिका...,फाइबरयुक्त खानाले कब्जियत कम गर्न मद्दत गर्छ भ...,पानी पिउँदा शरीरको तापक्रम मिल्छ र मिर्गौला स्...,बच्चाहरूमा कब्जियत रोक्न फाइबर र पानी दुवै चाह...,व्यायाम गर्दा आन्द्राको गतिविधि बढ्छ र कब्जियत...,health and nutrition
2,2,लघु व्यवसाय बचत खाताबाट personal account मा हु...,"हाम्रो वित्तीय म्यानुअल अनुसार, लघु व्यवसाय मा...","हाम्रो बजेट म्यानुअल अनुसार, मासिक आयको २० प्र...","व्यक्तिगत बैंकिङमा कर छुटको लागि, बैंकले दिने ...",लघु व्यवसाय मालिकले आफ्नो व्यावसायिक बचत खाताब...,बैंकिङ FAQ मा भनिएको छ कि emergency fund मा ६ ...,personal finance
3,3,हरितग्राम पहाडी क्षेत्रका लागि वन्यजन्तु संरक्...,वन्यजन्तु संरक्षण नोटिस: हरितग्राम पहाडी क्षेत...,वन्यजन्तु संरक्षण निर्देशिका: हरितग्राम पहाडी ...,जलवायु अनुकूलन नीति: हरितग्राम पहाडी क्षेत्रका...,मृदा संरक्षण नोटिस: हरितग्राम पहाडी क्षेत्रका ...,वायु प्रदूषण नियन्त्रण सूचना: हरितग्राम पहाडी ...,climate and environment
4,4,२०२३ को स्टडी जसमा १२० प्लटमा बर्ड सर्वे गरेर ...,२०२३ मा गरिएको एक फिक्शनल अध्ययनअनुसार प्राकृत...,हाम्रो अध्ययनले देखायो कि प्राकृतिक वन क्षेत्र...,नेपालको मध्यविन्दु क्षेत्रमा २०२३ को अध्ययनअनु...,प्राकृतिक वन र मानवीय हस्तक्षेप भएका क्षेत्रबी...,२०२३ मा गरिएको अध्ययनले प्राकृतिक वन क्षेत्रमा...,science and research
...,...,...,...,...,...,...,...,...
6416,6416,What are the specific requirements for a grade...,"नयाँ छात्रवृत्ति नियमावली अनुसार, कक्षा ८ मा उ...","नयाँ शैक्षिक नीति अनुसार, माध्यमिक तहका विद्या...",विद्यार्थीहरूको शैक्षिक विकासका लागि वार्षिक र...,कक्षा १० को अन्तिम परीक्षामा उत्कृष्ट प्रदर्शन...,विद्यालय प्रशासनले प्रत्येक शैक्षिक सत्रको अन्...,education
6417,6417,What are the specific structural characteristi...,यो अध्ययनले 'नियो-जस्टिस डिक्री' को संरचनात्मक...,यो अध्ययनले 'नियो-जस्टिस एक्ट' को कार्यान्वयन ...,प्रस्तुत अनुसन्धानले 'नियो-जस्टिस प्रोटोकल' अन...,यस शोधपत्रले 'नियो-जस्टिस रेगुलेसन' को ऐतिहासि...,अध्ययनले 'नियो-जस्टिस फ्रेमवर्क' को प्राविधिक ...,law and policy
6418,6418,Is it true that the Kirat period played a foun...,तपाईँले सोध्नुभएको कुरा सही हो। ऐतिहासिक तथ्यह...,नेपालको सांस्कृतिक इतिहासमा लिच्छवि काललाई 'स्...,मल्ल कालमा काठमाडौँ उपत्यकाका विभिन्न शहरहरूमा...,नेपालका विभिन्न जातजातिहरूबीचको सांस्कृतिक आदा...,प्राचीन कालमा नेपालमा विभिन्न किसिमका लिपि र भ...,history and culture
6419,6419,Does the Agro-Grow syrup by Himalayan Bliss sc...,हिमालयन ब्लिसले जारी गरेको वैज्ञानिक प्रतिवेदन...,हिमालयन ब्लिसले आफ्नो नयाँ 'एग्रो-ग्रो' सिर्पक...,"एउटा हालै सम्पन्न अनुसन्धानका अनुसार, 'एग्रो-ग...",कृषि विज्ञहरूले 'एग्रो-ग्रो' सिर्पको प्रयोग गर...,नेपालका विभिन्न भागमा गरिएको एक सर्वेक्षणले 'ए...,products and services
6420,6420,What is the potential connection between Type ...,यदि तपाईँलाई मधुमेह (Diabetes) को समस्या छ र श...,भिटामिन सी को सेवनले इम्युनिटी प्रणालीलाई बलिय...,क्याल्सियम र भिटामिन डी को संयुक्त सेवनले हड्ड...,आइरनको कमीले गर्दा शरीरमा थकान र कमजोरी महसुस ...,ओमेगा-३ फ्याट्टी एसिड मुटुको स्वास्थ्यका लागि ...,personal finance

In [93]:
query = """
select
    domain,
    count(*) as num_examples,
    round(count(*) / sum(count(*)) over() * 100, 2) as percent,
from df
group by 1
order by 2 desc
"""
print(duckdb.query(query).df().to_markdown(index=False))

| domain                    |   num_examples |   percent |
|:--------------------------|---------------:|----------:|
| work and livelihoods      |            438 |      6.82 |
| energy and infrastructure |            435 |      6.77 |
| personal finance          |            432 |      6.73 |
| Nepal civic services      |            430 |      6.7  |
| climate and environment   |            430 |      6.7  |
| products and services     |            429 |      6.68 |
| education                 |            429 |      6.68 |
| science and research      |            428 |      6.67 |
| travel and geography      |            428 |      6.67 |
| technology                |            427 |      6.65 |
| law and policy            |            426 |      6.63 |
| community discussion      |            425 |      6.62 |
| agriculture               |            424 |      6.6  |
| health and nutrition      |            421 |      6.56 |
| history and culture       |            419 |      6.53 |

## Find duplicate queries

In [64]:
# lets see if there are exact matches first
query = """
select
    count(*) total_rows,
    count(distinct query) total_unique_queries,
from df
"""
duckdb.query(query).df()

   total_rows  total_unique_queries
0        6421                  6421

In [ ]:
# to create a strong testing set, we'll use a modern multi-lingual model as a baseline
# in the test set only those rows will be present whose query-doc similarity is less than max(query to negatives)
# for train and valid, we'll partiton the remaining rows
from sentence_transformers import SentenceTransformer
encoder = SentenceTransformer("intfloat/multilingual-e5-small", device="cuda:1")

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

In [ ]:
# they recommend to prefix the query and document when encoding but it is not configured by
# default, so we manually add these
encoder.prompts = {"query": "query: ", "document": "passage: "}
encoder.default_prompt_name = "query"

In [65]:
def embed(df, encoder):
    query_embeddings = encoder.encode_query(df['query'].tolist())
    pos_embeddings = encoder.encode_document(df['positive'].tolist())
    neg_embeddings = encoder.encode_document(df['negative_1'].tolist())
    neg2_embeddings = encoder.encode_document(df['negative_2'].tolist())
    neg3_embeddings = encoder.encode_document(df['negative_3'].tolist())
    neg4_embeddings = encoder.encode_document(df['negative_4'].tolist())
    return query_embeddings, pos_embeddings, neg_embeddings, neg2_embeddings, neg3_embeddings, neg4_embeddings

def df_with_pairwise_sim(df, encoder_name:str, query_embeddings, pos_embeddings, neg_embeddings, neg2_embeddings, neg3_embeddings, neg4_embeddings):
    query_pos_sim = encoder.similarity_pairwise(query_embeddings, pos_embeddings)
    query_neg_sim = encoder.similarity_pairwise(query_embeddings, neg_embeddings)
    query_neg2_sim = encoder.similarity_pairwise(query_embeddings, neg2_embeddings)
    query_neg3_sim = encoder.similarity_pairwise(query_embeddings, neg3_embeddings)
    query_neg4_sim = encoder.similarity_pairwise(query_embeddings, neg4_embeddings)
    df[f'{encoder_name}_qp'] = query_pos_sim
    df[f'{encoder_name}_qn1'] = query_neg_sim
    df[f'{encoder_name}_qn2'] = query_neg2_sim
    df[f'{encoder_name}_qn3'] = query_neg3_sim
    df[f'{encoder_name}_qn4'] = query_neg4_sim
    df[f'{encoder_name}_qnmax'] = df[[f'{encoder_name}_qn1', f'{encoder_name}_qn2', f'{encoder_name}_qn3', f'{encoder_name}_qn4']].max(axis=1)
    return df

def populate_df(encoder, encoder_name, df):
    query_embeddings, pos_embeddings, neg_embeddings, neg2_embeddings, neg3_embeddings, neg4_embeddings = embed(df, encoder)
    return df_with_pairwise_sim(df, encoder_name, query_embeddings, pos_embeddings, neg_embeddings, neg2_embeddings, neg3_embeddings, neg4_embeddings)

In [ ]:
_ = populate_df(encoder, 'e5', df)

In [96]:
test_df = df.query("e5_qp < e5_qnmax")
test_sample_ids = test_df['sample_id']
train_df = df[~df['sample_id'].isin(test_sample_ids)]
print(f"total rows in test_df {len(test_df):,} and {len(train_df):,} in train_df")

counts = test_df['domain'].value_counts()

# Get the normalized values (percentages)
percentages = test_df['domain'].value_counts(normalize=True)

# Combine them into a DataFrame
test_stats_df = pd.DataFrame({
    'Domain': counts.index,
    'Count': counts.values,
    'Percentage (%)': (percentages * 100).round(2)
})

# Print as markdown
print(test_stats_df.to_markdown(index=False))

total rows in test_df 891 and 5,530 in train_df
| Domain                    |   Count |   Percentage (%) |
|:--------------------------|--------:|-----------------:|
| Nepal civic services      |      89 |             9.99 |
| agriculture               |      88 |             9.88 |
| products and services     |      83 |             9.32 |
| travel and geography      |      77 |             8.64 |
| community discussion      |      73 |             8.19 |
| health and nutrition      |      55 |             6.17 |
| law and policy            |      54 |             6.06 |
| work and livelihoods      |      52 |             5.84 |
| education                 |      50 |             5.61 |
| science and research      |      50 |             5.61 |
| personal finance          |      49 |             5.5  |
| technology                |      47 |             5.27 |
| history and culture       |      46 |             5.16 |
| climate and environment   |      41 |             4.6  |
| energy and infrastructure |      37 |             4.15 |

In [97]:
df.columns

Index(['sample_id', 'query', 'positive', 'negative_1', 'negative_2',
       'negative_3', 'negative_4', 'domain', 'e5_qp', 'e5_qn1', 'e5_qn2',
       'e5_qn3', 'e5_qn4', 'e5_qnmax', 'v3_qp', 'v3_qn1', 'v3_qn2', 'v3_qn3',
       'v3_qn4', 'v3_qnmax'],
      dtype='str')

In [110]:

final_cols = ['query', 'positive', 'negative_1', 'negative_2', 'negative_3', 'negative_4', 'domain']
features = datasets.Features({
    col: datasets.Value("string")
    for col in final_cols
})

ds = datasets.Dataset.from_pandas(train_df[final_cols], preserve_index=False, features=features).train_test_split(test_size=0.1, shuffle=True, seed=100)
ds['valid'] = ds['test']
ds['test'] = datasets.Dataset.from_pandas(test_df[final_cols], preserve_index=False, features=features)
ds

DatasetDict({
    train: Dataset({
        features: ['query', 'positive', 'negative_1', 'negative_2', 'negative_3', 'negative_4', 'domain'],
        num_rows: 4977
    })
    test: Dataset({
        features: ['query', 'positive', 'negative_1', 'negative_2', 'negative_3', 'negative_4', 'domain'],
        num_rows: 891
    })
    valid: Dataset({
        features: ['query', 'positive', 'negative_1', 'negative_2', 'negative_3', 'negative_4', 'domain'],
        num_rows: 553
    })
})

In [ ]:
ds.push_to_hub("jangedoo/sanoir-general")

In [ ]:
from sentence_transformers.sentence_transformer.evaluation import RerankingEvaluator

samples = []
negative_cols = [c for c in test_df.columns if c.startswith("negative")]
for _, row in test_df.iterrows():
    negatives = row[negative_cols].tolist()

    samples.append(
        {
            "query": row["query"],
            "positive": [row["positive"]], # important! it should be a list
            "negative": negatives,
        }
    )

In [115]:
reranking_evaluator = RerankingEvaluator(
    samples=samples,
    name="pos-vs-4-negs",
    at_k=5,
    batch_size=64,
    show_progress_bar=False
)
rerank_results = reranking_evaluator(encoder)
print(rerank_results)

{'pos-vs-4-negs_map': 0.4385147774036663, 'pos-vs-4-negs_mrr@5': 0.4385147774036663, 'pos-vs-4-negs_ndcg@5': 0.5820944567344883}

In [126]:
print(df[['query']].sample(10).to_markdown(index=False))

| query                                                                                                                                                                                                         |
|:--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Nepal mid-hill aalu cultivation ma drip irrigation le yield badhayo bhaneko compact study abstract dinus, method ra population specify garera.                                                                |
| What is the specific bone condition caused by vitamin D deficiency in children and how does it affect their physical structure?                                                                               |
| नेपालका वडा कार्यालयको भौतिक infrastructure ले नागरिकको local service experience मा कस्तो असर गर्छ? १२ जिल्लाका बिभिन्न वडामा गरिएको survey मा पूर्वाधार र सेवा सन्तुष्टीबीच positive relation देखिन्छ कि भनेर हेर्ने abstract खोज्दैछु। |
| विदेशी रोजगारीका लागि जाने अप्रवासी कामदारहरूलाई कुन भोकेशनल तालिम कार्यक्रमले माइग्रेसन कागजात तयारीका लागि सहायक हटलाइन उपलब्ध गराउँछ र त्यस्तो तालिम सञ्चालन गर्ने संस्थाको नाम के हो?                                             |
| How do hydropower plants help in maintaining grid stability through the national transmission lines?                                                                                                          |
| बाढीको समयमा स्थानीय हाइड्रोपावरले टेलिकम टावरलाई NEA ग्रिड कटौती हुँदा पनि माइक्रोग्रिडबाट सिधा पावर दिएर सञ्चार सेवा चलिरहेको प्रमाण खोज्नुहोस्।                                                                                  |
| What scientific evidence links rising temperatures in the Himalayan region to the risk of glacial lake outbursts in Nepal?                                                                                    |
| नेपालका maize किसानको मकै खेतीमा cover cropping गर्दा माटो carbon बढ्छ भन्ने study देखाउने service वा product page कता छ?                                                                                               |
| वृद्धावस्थाका महिलाहरूमा vitamin D fortified milk को controlled nutritional intervention ले muscle strength मा सुधार गर्छ भन्ने cautious evidence-based explainer खोज्दैछु।                                                 |
| Nepal को Terai मा climate-resilient rice cultivation को लागि irrigation प्रणाली र yield अध्ययन गर्ने related scientific work खोज्दैछु।                                                                               |